### PR TITLE
LinuxAdmin.run/run! used to work, put it back via delegation

### PR DESCRIPTION
**Pull request by jrafanie**
This regressed here:
https://github.com/ManageIQ/linux_admin/commit/9e7d11322d793fe572a0cb94ffcded36bb4bfb94

Existing scripts that worked on 0.14.0 would be broken by 0.15.0+

### CODE REVIEW

**Comment by jrafanie** [comment]
@bdunne @carbonin can you review?

**Comment by carbonin** [comment]
I know, I did that on purpose. What is this breaking?

ref: https://github.com/ManageIQ/manageiq/pull/6628

**Comment by Fryguy** [comment]
Was it deprecated properly and released with a proper semver change?

**Comment by Fryguy** [comment]
Since we are less than a 1.0 release, according to SemVer, we can *technically* break in a minor release, but the better way would have been to deprecate it until 1.0 where we break it.

**Comment by Fryguy** [comment]
@jrafanie Can you please add a deprecation warning?

**Comment by jrafanie** [comment]
> @jrafanie Can you please add a deprecation warning?

Done, rubygem's deprecate requires the month and year, which is useless... but it's a simple dsl baked into all modern rubies.

**Pull request merged**
