### PR TITLE
Added iburst parameter while setting  ntp servers

### PR DESCRIPTION
**Pull request by yrudman**
https://bugzilla.redhat.com/show_bug.cgi?id=1308606

### CODE REVIEW

**Comment by chessbyte** [comment]
@jrafanie please review

**Comment by jrafanie** [comment]
@yrudman I think we need to update this spec to confirm we're writing with the iburst value.

https://github.com/ManageIQ/linux_admin/blob/master/spec/chrony_spec.rb#L36

cc @carbonin

**Comment by carbonin** [comment]
I `expect` we would have to update the specs :trollface: 
Are we not running travis here? @bdunne

**Comment by jrafanie** [comment]
trying to kick start travis

**Comment by yrudman** [comment]
Modified chrony_spec to check iburst parameter

**Comment by carbonin** [comment]
:+1:

**Comment by bdunne** [comment]
:+1:

**Pull request merged**
