### PR TITLE
Introduce enable_dhcp6 method

### PR DESCRIPTION
**Pull request by isimluk**
For enabling DHCPv6 client.

@miq-bot add_label enhancement

### CODE REVIEW

**Comment by carbonin** [comment]
Do we really want this to be separate?

I feel like enabling dhcp should be one concept and then dependent on what kind of dhcp server is on the user's network.

Do you think there is a use case for specifically enabling dhcpv4 and not dhcpv6 (or the other way around)?

**Comment by isimluk** [comment]
I work on IPv6-only enablement. So, I guess having only single one stack is a thing. No strong opinion though. The downside is only having extra dhclient running. 

We may learn more once this gets some adoption, to a certain extent we are blind of how the set-up will look like.

People on the internet sometimes ask for ipv4 static and ipv6 dhcp settings or contrawise.

Look at https://github.com/ManageIQ/manageiq-gems-pending/pull/99, I think the dialog like this will be easy to comprehend for end-user.

**Comment by carbonin** [comment]
> People on the internet sometimes ask for ipv4 static and ipv6 dhcp settings or contrawise.

I feel like the way this is now, we won't be able to support such a thing. For example, setting either protocol to dhcp removes the `DNS` and `DOMAIN` keys that may have been set when configuring static for the other protocol.

**Comment by isimluk** [comment]
To a certain extent. The DNS should be managed by different set of methods in NetworkInterface. That is evidenced by calls of `resolv = LinuxAdmin::Dns.new; resolv.search_order = []; resolv.nameservers = []; resolv.save` in multiple places in `appliance_console`.

The thing underneath works like this:
 - dns entries in network-scripts gets appended to the `resolve.conf`
 - then dhcp, dhcpv6 appends to `resolve.conf`
 - `resolve.conf` can hold only three entries

It's lot of mess. I guess our code is only to help users to set-up simple networking scenarios when they first boot. I wish we never had this code on our own.

Should I merge the `enable_dhcp6` to enable_dhcp` then?

**Comment by carbonin** [comment]
Let's do that then.

Probably a separate PR, but it sounds like we should back the `NetworkInterface#dns=` and `NetworkInterface#search_order=` methods with `LinuxAdmin::Dns` to make sure we have the "right" source of information.

From what you described, the network-scripts keys for these are just fronts for configuring `resolve.conf` properly so it feels like our abstraction should act the same way. Then maybe we remove the ability to mess with nameservers and search order entirely from network interfaces in the future.

For this PR I guess we can leave it the way it is. That way in the :sparkles: future :sparkles: when we implement :point_up: the DNS and DOMAIN keys will be removed from the network configuration if they were already there.

**Pull request merged**
